# Generated by Django 4.1.5 on 2023-01-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="customerID",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="productID",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="productID",
        ),
        migrations.AlterModelTable(
            name="customer",
            table=None,
        ),
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
        migrations.DeleteModel(
            name="Sale",
        ),
    ]
