# Generated by Django 4.1.5 on 2023-01-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
