# Generated by Django 4.1.5 on 2023-01-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
